# Generated by Django 3.0.3 on 2020-03-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default='A SeeFood restaurant', max_length=10000),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('FF', 'Fast Food'), ('CD', 'Casual Dining'), ('ET', 'Ethnic'), ('NA', 'Not Indicated')], default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='seefood_rating',
            field=models.DecimalField(decimal_places=1, default=5, help_text='the rating uniquely given by SeeFood', max_digits=3),
        ),
    ]
