# Generated by Django 3.0.3 on 2020-03-25 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_auto_20200325_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(choices=[('B', 'Beef'), ('C', 'Chicken'), ('P', 'Pork')], max_length=2)),
                ('calories', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carb', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('classification', models.CharField(choices=[('VE', 'Vegan'), ('GF', 'Gluten Free')], max_length=3)),
                ('allergen', models.ManyToManyField(to='navigation.Allergen')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.Restaurant')),
            ],
        ),
    ]
